In [1]:
# Script di avvio sta in:
get_ipython().profile_dir.startup_dir

'/home/ale/.ipython/profile_default/startup'

In [2]:
matrix_a=np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])

In [3]:
matrix_a

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [4]:
np.ptp(matrix_a)

9

In [5]:
np.ptp(matrix_a, axis=0)

array([3, 6, 6, 6, 9])

In [6]:
np.ptp(matrix_a, axis=1)

array([3, 7, 8])

In [9]:
np.sort(matrix_a, axis=None)

array([0, 0, 0, 1, 1, 2, 3, 3, 3, 4, 5, 6, 6, 8, 9])

In [28]:
np.percentile(matrix_a,70)

4.799999999999999

In [22]:
import cv2, numpy

In [10]:
im_g=cv2.imread("../../Scaricati/smallgray.png",0)
print(im_g)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [25]:
ims = numpy.vstack((im_g,im_g))
print(ims)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [1]:
from urllib.request import urlopen
import json

In [2]:
url = 'https://www.data.qld.gov.au/api/3/action/datastore_search?resource_id=7afe7233-fae0-4024-bc98-3a72f05675bd&limit=5'
urlresult = urlopen( url )
urlresult

In [3]:
raw_data = urlresult.read()
raw_data

b'{"help": "https://www.data.qld.gov.au/api/3/action/help_show?name=datastore_search", "success": true, "result": {"include_total": true, "limit": 5, "records_format": "objects", "resource_id": "7afe7233-fae0-4024-bc98-3a72f05675bd", "total_estimation_threshold": null, "records": [{"_id":181389935,"Site":"abellpoint","Seconds":"1711202400","DateTime":"2024-03-24T00:00","Water Level":"2.261","Prediction":"2.169","Residual":"0.092","Latitude":"-20.2608","Longitude":"148.7103"},{"_id":181389936,"Site":"abellpoint","Seconds":"1711203000","DateTime":"2024-03-24T00:10","Water Level":"2.181","Prediction":"2.084","Residual":"0.097","Latitude":"-20.2608","Longitude":"148.7103"},{"_id":181389937,"Site":"abellpoint","Seconds":"1711203600","DateTime":"2024-03-24T00:20","Water Level":"2.093","Prediction":"1.997","Residual":"0.096","Latitude":"-20.2608","Longitude":"148.7103"},{"_id":181389938,"Site":"abellpoint","Seconds":"1711204200","DateTime":"2024-03-24T00:30","Water Level":"1.977","Prediction"

In [4]:
json_data = json.loads( raw_data )
json_data

{'help': 'https://www.data.qld.gov.au/api/3/action/help_show?name=datastore_search',
 'success': True,
 'result': {'include_total': True,
  'limit': 5,
  'records_format': 'objects',
  'resource_id': '7afe7233-fae0-4024-bc98-3a72f05675bd',
  'total_estimation_threshold': None,
  'records': [{'_id': 181389935,
    'Site': 'abellpoint',
    'Seconds': '1711202400',
    'DateTime': '2024-03-24T00:00',
    'Water Level': '2.261',
    'Prediction': '2.169',
    'Residual': '0.092',
    'Latitude': '-20.2608',
    'Longitude': '148.7103'},
   {'_id': 181389936,
    'Site': 'abellpoint',
    'Seconds': '1711203000',
    'DateTime': '2024-03-24T00:10',
    'Water Level': '2.181',
    'Prediction': '2.084',
    'Residual': '0.097',
    'Latitude': '-20.2608',
    'Longitude': '148.7103'},
   {'_id': 181389937,
    'Site': 'abellpoint',
    'Seconds': '1711203600',
    'DateTime': '2024-03-24T00:20',
    'Water Level': '2.093',
    'Prediction': '1.997',
    'Residual': '0.096',
    'Latitude': 

In [6]:
# covert to string to print in a compact format
json_string = json.dumps( json_data)
print( json_string)

{"help": "https://www.data.qld.gov.au/api/3/action/help_show?name=datastore_search", "success": true, "result": {"include_total": true, "limit": 5, "records_format": "objects", "resource_id": "7afe7233-fae0-4024-bc98-3a72f05675bd", "total_estimation_threshold": null, "records": [{"_id": 181389935, "Site": "abellpoint", "Seconds": "1711202400", "DateTime": "2024-03-24T00:00", "Water Level": "2.261", "Prediction": "2.169", "Residual": "0.092", "Latitude": "-20.2608", "Longitude": "148.7103"}, {"_id": 181389936, "Site": "abellpoint", "Seconds": "1711203000", "DateTime": "2024-03-24T00:10", "Water Level": "2.181", "Prediction": "2.084", "Residual": "0.097", "Latitude": "-20.2608", "Longitude": "148.7103"}, {"_id": 181389937, "Site": "abellpoint", "Seconds": "1711203600", "DateTime": "2024-03-24T00:20", "Water Level": "2.093", "Prediction": "1.997", "Residual": "0.096", "Latitude": "-20.2608", "Longitude": "148.7103"}, {"_id": 181389938, "Site": "abellpoint", "Seconds": "1711204200", "DateT

In [25]:
records = json_data['result']['records']
first_record = records[0]
first_record

{'_id': 181389935,
 'Site': 'abellpoint',
 'Seconds': '1711202400',
 'DateTime': '2024-03-24T00:00',
 'Water Level': '2.261',
 'Prediction': '2.169',
 'Residual': '0.092',
 'Latitude': '-20.2608',
 'Longitude': '148.7103'}

In [27]:
site = first_record['Site']
dateTime = first_record['DateTime']
waterLevel = first_record['Water Level']
prediction = first_record['Prediction']
residual = first_record['Residual']
print(site)
print(residual)

abellpoint
0.092


In [29]:
# Create a list with the desired data points per every record:
records_data = []
for record in records:
    recordData = [
            first_record['Site'],
            first_record['DateTime'],
            first_record['Water Level'],
            first_record['Prediction'],
            first_record['Residual']        
    ]
    records_data.append( recordData)

print( records_data)


[['abellpoint', '2024-03-24T00:00', '2.261', '2.169', '0.092'], ['abellpoint', '2024-03-24T00:00', '2.261', '2.169', '0.092'], ['abellpoint', '2024-03-24T00:00', '2.261', '2.169', '0.092'], ['abellpoint', '2024-03-24T00:00', '2.261', '2.169', '0.092'], ['abellpoint', '2024-03-24T00:00', '2.261', '2.169', '0.092']]


In [17]:
matr = [[11,2,4],[4,5,6],[10,8,-12]]
matr4 = [[11,2,4,5],[4,9,5,6],[10,19,8,-12],[77,-59,18,52]]

def diagonalDifference(arr):
    # Write your code here
    diag1 = arr[0][0] + arr[1][1] + arr[2][2]
    diag2 = arr[0][2] + arr[1][1] + arr[2][0]
    diff = abs(diag1 - diag2)
    return diff

In [18]:
len(matr4)

4

In [13]:
diagonalDifference(matr)

15

In [20]:
def test(arr):
    diag1 = 0
    for i in range(0,len(arr)):
        diag1+=arr[i][i]
    diag2 = 0
    for i in range(0,len(arr)):
        diag2+=arr[i][-(i+1)]
    diff = diag1 - diag2
    return abs(diff)

test(matr)



4

In [21]:
matr4

[[11, 2, 4, 5], [4, 9, 5, 6], [10, 19, 8, -12], [77, -59, 18, 52]]

In [26]:
matr4[0][-(0+1)]

5

In [28]:
matr4[2][-(2+1)]

19

In [11]:
diff

15

In [3]:
mialista = [1,1,0,-1,-1]

neg = 0
pos = 0
zer = 0
for el in mialista:
    if el < 0:
        neg += 1
    elif el == 0:
        zer += 1
    elif el > 0:
        pos += 1

print(str(round(neg/len(mialista),6)))
print(zer/len(mialista))
print(pos/len(mialista))

0.4
0.2
0.4


In [20]:
import pandas as pd
import numpy as np

In [13]:
df1 = pd.DataFrame([[1,2,3],[4,5,6]],['ind1','ind2'],['pippo','paperotta','topa pelosa'])

In [14]:
df1

pippo  paperotta  topa pelosa
ind1      1          2            3
ind2      4          5            6

In [29]:
seria = np.array([[1,2,3],[4,5,6]])
seria2 = np.array([[5,6,7],[4,5,6]])

In [30]:
seria2 - seria

array([[4, 4, 4],
       [0, 0, 0]])

In [31]:
np.sum(seria2 - seria)

np.int64(12)

In [32]:
range(0,4)

range(0, 4)

In [33]:
list(range(0,4))

[0, 1, 2, 3]

In [34]:
import random

In [39]:
random.randint(5,1)

ValueError: empty range in randrange(5, 2)